import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const source = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MovieDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={source.className}>
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
