import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";

const source = Source_Sans_3({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "MovieDB",
  description: "Generated by create next app",
};

const toastOptions = {
  classNames: {
    error: "bg-black border-none",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={source.className}>
        <Providers>
          <Header />
          <main>{children}</main>
          <Toaster toastOptions={toastOptions} />
        </Providers>
      </body>
    </html>
  );
}
